apiVersion: v1
kind: ConfigMap
metadata:
  name: kcl-plugin-config
  namespace: argocd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: kcl
    spec:
      version: v1.0
      generate:
        command: ["sh", "-c"]
        args:
          - |
            tempfile=$(mktemp)
            kcl run -q -o $tempfile
            error=$?
            if [ $error -eq 0 ]; then
              cat $tempfile
              rm $tempfile
            fi
            exit $error
